# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/suman/surface_reconstruction

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/suman/surface_reconstruction

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suman/surface_reconstruction/CMakeFiles /home/suman/surface_reconstruction/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/suman/surface_reconstruction/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named surface_reconstruction

# Build rule for target.
surface_reconstruction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 surface_reconstruction
.PHONY : surface_reconstruction

# fast build rule for target.
surface_reconstruction/fast:
	$(MAKE) -f CMakeFiles/surface_reconstruction.dir/build.make CMakeFiles/surface_reconstruction.dir/build
.PHONY : surface_reconstruction/fast

#=============================================================================
# Target rules for targets named segmentation_DON

# Build rule for target.
segmentation_DON: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 segmentation_DON
.PHONY : segmentation_DON

# fast build rule for target.
segmentation_DON/fast:
	$(MAKE) -f CMakeFiles/segmentation_DON.dir/build.make CMakeFiles/segmentation_DON.dir/build
.PHONY : segmentation_DON/fast

grid_projection_surface.o: grid_projection_surface.cpp.o

.PHONY : grid_projection_surface.o

# target to build an object file
grid_projection_surface.cpp.o:
	$(MAKE) -f CMakeFiles/surface_reconstruction.dir/build.make CMakeFiles/surface_reconstruction.dir/grid_projection_surface.cpp.o
.PHONY : grid_projection_surface.cpp.o

grid_projection_surface.i: grid_projection_surface.cpp.i

.PHONY : grid_projection_surface.i

# target to preprocess a source file
grid_projection_surface.cpp.i:
	$(MAKE) -f CMakeFiles/surface_reconstruction.dir/build.make CMakeFiles/surface_reconstruction.dir/grid_projection_surface.cpp.i
.PHONY : grid_projection_surface.cpp.i

grid_projection_surface.s: grid_projection_surface.cpp.s

.PHONY : grid_projection_surface.s

# target to generate assembly for a file
grid_projection_surface.cpp.s:
	$(MAKE) -f CMakeFiles/surface_reconstruction.dir/build.make CMakeFiles/surface_reconstruction.dir/grid_projection_surface.cpp.s
.PHONY : grid_projection_surface.cpp.s

region_DON.o: region_DON.cpp.o

.PHONY : region_DON.o

# target to build an object file
region_DON.cpp.o:
	$(MAKE) -f CMakeFiles/segmentation_DON.dir/build.make CMakeFiles/segmentation_DON.dir/region_DON.cpp.o
.PHONY : region_DON.cpp.o

region_DON.i: region_DON.cpp.i

.PHONY : region_DON.i

# target to preprocess a source file
region_DON.cpp.i:
	$(MAKE) -f CMakeFiles/segmentation_DON.dir/build.make CMakeFiles/segmentation_DON.dir/region_DON.cpp.i
.PHONY : region_DON.cpp.i

region_DON.s: region_DON.cpp.s

.PHONY : region_DON.s

# target to generate assembly for a file
region_DON.cpp.s:
	$(MAKE) -f CMakeFiles/segmentation_DON.dir/build.make CMakeFiles/segmentation_DON.dir/region_DON.cpp.s
.PHONY : region_DON.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... surface_reconstruction"
	@echo "... segmentation_DON"
	@echo "... grid_projection_surface.o"
	@echo "... grid_projection_surface.i"
	@echo "... grid_projection_surface.s"
	@echo "... region_DON.o"
	@echo "... region_DON.i"
	@echo "... region_DON.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

